
name: MLflow Project CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn mlserver

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifacts
          path: |
            MLProject/mlruns
            MLProject/mlruns/**
            MLProject/model
            MLProject/model/**

      - name: Build Docker image with MLflow
        run: |
          mlflow models build-docker -m MLProject/model -n ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest --enable-mlserver

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest
