
name: MLflow Project CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifacts
          path: |
            MLProject/mlruns
            MLProject/mlruns/**
            MLProject/mlflow.db

      - name: Get latest MLflow run ID
        id: get_run
        run: |
          cd MLProject
          RUN_ID=$(find mlruns -mindepth 3 -maxdepth 3 -type d | head -n 1 | awk -F'/' '{print $3}')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run id: $RUN_ID"

      - name: Build Docker image with MLflow
        run: |
          cd MLProject
          mlflow models build-docker -m runs:/${{ steps.get_run.outputs.run_id }}/model -n ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest --enable-mlserver

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest
